### ISSUE TITLE
account cannot be persisted and dbus socket missing

### ISSUE THREAD

**Issue by domi-a** [hvalev/spotifyd-docker#103]
i'm trying to setup a raspberry pi with spotifyd and some kind of cli/dbus/api access to play songs as a kids device.
i preferredly use docker images to install software on any headless devices.
i found yours and it seems more up to date than most others, so i gave it a try.

image: hvalev/spotifyd-alsa 
can be started, can play music with spotify connect but forgets its cretentials on restart.
as of recent changes by spotify i did understand that that we have to use zeronfig.
so no username or password in spotifyd.config 
but  configured cache_path = "cache_directory" and use_keyring = true
cache_directory seems not get created by spotifyd, so i create one and mount it into the container.
seems to have write permissions problem, so i ran it with the pi user like this:
```
services:
  spotifyd:
    container_name: spotify
    restart: "unless-stopped"
    user: 1000:1000
    image: hvalev/spotifyd-alsa
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /usr/share/alsa:/usr/share/alsa
      - ./spotifyd.conf:/etc/spotifyd.conf
      - ./cache_directory:/cache_directory
      - /etc/asound.conf:/etc/asound.conf
    group_add:
      - 29
```
which can cache music and volume but i guess no credentials or i guess a auth-token.
so everytime i restart the device or the container i have to use spotify on my phone.
but unlikely this is totally out of my usecase.
i cant find the folder to mount into the container so that the auth-token is persisted.

.
.

and i think this would not be enough to fix it as i didnt have any dbus service linked into it yet - as i want to control spotify with some hardware buttons.
of course i tried the image: hvalev/spotifyd-alsa-dbus but that got me even into more trouble as that doesn't match up with the permissions of the set user 1000.
and that is causing errors with not existing /var/run/dbus/system_bus_socket which is constantly restarting and messing up my spotify account, which now got locked by fraud detection.
but i think the dbus thing can only be resolved when the account persistany is in working condition.

can you tell me how this indendet to setup with account persistancy?
