### ISSUE TITLE
spotifyd crashes on startup

### ISSUE THREAD

**Issue by agneevX** [hvalev/spotifyd-docker#20]
Hi,

I just set up spotifyd, however it seems to crash immediately:

```
Loading config from "/etc/spotifyd.conf",
The application panicked (crashed).,
Message:  called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" },
Location: /usr/src/spotifyd/vendor/librespot-core/src/cache.rs:30,
,
Backtrace omitted.,
Run with RUST_BACKTRACE=1 environment variable to display it.,
Run with RUST_BACKTRACE=full to include source snippets.,
The application panicked (crashed).,
Message:  called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" },
Location: /usr/src/spotifyd/vendor/librespot-core/src/cache.rs:30,
,
Backtrace omitted.,
Run with RUST_BACKTRACE=1 environment variable to display it.,
Run with RUST_BACKTRACE=full to include source snippets.,
Loading config from "/etc/spotifyd.conf"
```
```yml
  spotifyd:
    container_name: spotifyd
    image: hvalev/spotifyd-alsa
    restart: unless-stopped
    group_add:
      - 29
    # tmpfs:
    #   - /cache:size=64m
    volumes:
      - /opt/appdata/spotifyd/spotifyd.conf:/etc/spotifyd.conf
      - /usr/share/alsa:/usr/share/alsa:ro
    devices:
      - /dev/snd:/dev/snd
  ````
