### ISSUE TITLE
Pulseaudio example config

### ISSUE THREAD

**Issue by rp86** [hvalev/spotifyd-docker#42]
Hi, thanks for this docker container! I was previously using synclpz/spotifyd-pulseaudio but it hasn't been updated for a while. I was able to get your container working successfully using the following compose file. I have tried to strip out anything extra from the old config, but there might be some config here that isn't absolutely required. 

AUDIO_GRP, PUID, PGID and USERDIR must be defined as environment variables or replaced with the correct values in the docker compose file. 

```
version: "3.5"
services:
  spotify:
    container_name: spotify
    restart: always
    image: hvalev/spotifyd-pulseaudio
    user: ${PUID}:${PGID}
#    network_mode: host #disabling to only show logged in user in spotify app (I run multiple containers at once with different user logins)
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - ${AUDIO_GRP}
    environment: 
      - PULSE_SERVER=unix:/tmp/pulseaudio.socket
      - PULSE_COOKIE=/tmp/pulseaudio.cookie
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulseaudio.socket
      - ${USERDIR}/docker/spotifyd/spotifyd.conf:/etc/spotifyd.conf
```
