### ISSUE TITLE
Alsa device not working 

### ISSUE THREAD

**Issue by pgcudahy** [hvalev/spotifyd-docker#48]
Hello, I've got an ubuntu setup with working audio but trying to get a spotifyd.conf that works with this container. Currently I have a USB soundcard that is labeled as "default" by `aplay -L` and `aplay -D default /usr/share/sounds/alsa/Front_Center.wav` works. My spotifyd.conf is
```
username= XXX
password = XXX
backend = "alsa"
device = "default"
control = "default"
mixer = "PCM"
volume_controller = "alsa"
device_name = "YYY"
bitrate = 160
no_audio_cache = true
initial_volume = "90"
volume_normalisation = true
normalisation_pregain = -10
zeroconf_port = 1234
device_type = "computer"
```
And my docker-compose.yml is
```
  spotifyd:
    container_name: spotifyd
    image: hvalev/spotifyd-alsa
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /usr/share/alsa:/usr/share/alsa
      - /home/pgcudahy/spotifyd/spotifyd.conf:/etc/spotifyd.conf
      - /etc/asound.conf:/etc/asound.conf
    group_add:
      - audio
    restart: unless-stopped
```
But it doesn't work and the logs are
```
Loading config from "/etc/spotifyd.conf"
No proxy specified
Using alsa volume controller.
Connecting to AP "ap.spotify.com:443"
Authenticated as "XXX" !
Country: "US"
Using Alsa sink with format: S16
Couldn't set volume: Error("snd_mixer_attach", Sys(EINVAL))
ALSA lib dlmisc.c:170:(snd_dlsym_verify) unable to verify version for symbol snd_func_private_integer
ALSA lib conf.c:4556:(_snd_config_evaluate) symbol snd_func_private_integer is not defined inside (null)
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such device or address
ALSA lib conf.c:3694:(snd_config_hook_load) Unable to expand filenames in the pre-load section
ALSA lib conf.c:3572:(snd_config_hooks_call) function snd_config_hook_load_for_all_cards returned error: No such device or address
ALSA lib control.c:1264:(snd_ctl_open_conf) Invalid type for CTL default definition
```

What am I getting wrong?
